apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: flask-example-staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: registry.gitlab.com/aminberge/flask-example:latest
        ports:
        - containerPort: 8000
        env:
        - name: FLASK_ENV
          value: "staging"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: database_url
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"