apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: flask-example-prod  # Changed from staging to prod
spec:
  selector:
    app: flask-app
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP